stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  image: node:latest
  script:
    - npm install
    - echo "Build step (add your build commands here)"

jest_tests:
  stage: test
  image: node:latest
  script:
    - npm install
    - npm test

deploy_job:
  stage: deploy
  image: php:7.4-cli
  before_script:
    - apt-get update && apt-get install -y unzip git  # Install unzip if needed
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install
  script:
    - echo "Deploying to production..."
    - cd app/api/pull_to_prod
    - php index.php
